// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: multiplier.proto

package multiplier

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MultiplyFloatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *float32 `protobuf:"fixed32,1,req,name=a" json:"a,omitempty"`
	B *float32 `protobuf:"fixed32,2,req,name=b" json:"b,omitempty"`
}

func (x *MultiplyFloatMessage) Reset() {
	*x = MultiplyFloatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiplier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplyFloatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyFloatMessage) ProtoMessage() {}

func (x *MultiplyFloatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_multiplier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplyFloatMessage.ProtoReflect.Descriptor instead.
func (*MultiplyFloatMessage) Descriptor() ([]byte, []int) {
	return file_multiplier_proto_rawDescGZIP(), []int{0}
}

func (x *MultiplyFloatMessage) GetA() float32 {
	if x != nil && x.A != nil {
		return *x.A
	}
	return 0
}

func (x *MultiplyFloatMessage) GetB() float32 {
	if x != nil && x.B != nil {
		return *x.B
	}
	return 0
}

type MultiplyFloatResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R *float32 `protobuf:"fixed32,1,req,name=r" json:"r,omitempty"`
}

func (x *MultiplyFloatResult) Reset() {
	*x = MultiplyFloatResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiplier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplyFloatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyFloatResult) ProtoMessage() {}

func (x *MultiplyFloatResult) ProtoReflect() protoreflect.Message {
	mi := &file_multiplier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplyFloatResult.ProtoReflect.Descriptor instead.
func (*MultiplyFloatResult) Descriptor() ([]byte, []int) {
	return file_multiplier_proto_rawDescGZIP(), []int{1}
}

func (x *MultiplyFloatResult) GetR() float32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

var File_multiplier_proto protoreflect.FileDescriptor

var file_multiplier_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x32, 0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x02, 0x52, 0x01, 0x62, 0x22, 0x23, 0x0a, 0x13, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x79, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x01, 0x72, 0x32, 0x4a, 0x0a, 0x0a, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0d, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x79, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x15, 0x2e, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x79, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x14, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
}

var (
	file_multiplier_proto_rawDescOnce sync.Once
	file_multiplier_proto_rawDescData = file_multiplier_proto_rawDesc
)

func file_multiplier_proto_rawDescGZIP() []byte {
	file_multiplier_proto_rawDescOnce.Do(func() {
		file_multiplier_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiplier_proto_rawDescData)
	})
	return file_multiplier_proto_rawDescData
}

var file_multiplier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multiplier_proto_goTypes = []interface{}{
	(*MultiplyFloatMessage)(nil), // 0: MultiplyFloatMessage
	(*MultiplyFloatResult)(nil),  // 1: MultiplyFloatResult
}
var file_multiplier_proto_depIdxs = []int32{
	0, // 0: Multiplier.MultiplyFloat:input_type -> MultiplyFloatMessage
	1, // 1: Multiplier.MultiplyFloat:output_type -> MultiplyFloatResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiplier_proto_init() }
func file_multiplier_proto_init() {
	if File_multiplier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multiplier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplyFloatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiplier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplyFloatResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiplier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiplier_proto_goTypes,
		DependencyIndexes: file_multiplier_proto_depIdxs,
		MessageInfos:      file_multiplier_proto_msgTypes,
	}.Build()
	File_multiplier_proto = out.File
	file_multiplier_proto_rawDesc = nil
	file_multiplier_proto_goTypes = nil
	file_multiplier_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MultiplierClient is the client API for Multiplier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MultiplierClient interface {
	MultiplyFloat(ctx context.Context, in *MultiplyFloatMessage, opts ...grpc.CallOption) (*MultiplyFloatResult, error)
}

type multiplierClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplierClient(cc grpc.ClientConnInterface) MultiplierClient {
	return &multiplierClient{cc}
}

func (c *multiplierClient) MultiplyFloat(ctx context.Context, in *MultiplyFloatMessage, opts ...grpc.CallOption) (*MultiplyFloatResult, error) {
	out := new(MultiplyFloatResult)
	err := c.cc.Invoke(ctx, "/Multiplier/MultiplyFloat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiplierServer is the server API for Multiplier service.
type MultiplierServer interface {
	MultiplyFloat(context.Context, *MultiplyFloatMessage) (*MultiplyFloatResult, error)
}

// UnimplementedMultiplierServer can be embedded to have forward compatible implementations.
type UnimplementedMultiplierServer struct {
}

func (*UnimplementedMultiplierServer) MultiplyFloat(context.Context, *MultiplyFloatMessage) (*MultiplyFloatResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiplyFloat not implemented")
}

func RegisterMultiplierServer(s *grpc.Server, srv MultiplierServer) {
	s.RegisterService(&_Multiplier_serviceDesc, srv)
}

func _Multiplier_MultiplyFloat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyFloatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplierServer).MultiplyFloat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Multiplier/MultiplyFloat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplierServer).MultiplyFloat(ctx, req.(*MultiplyFloatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Multiplier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Multiplier",
	HandlerType: (*MultiplierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MultiplyFloat",
			Handler:    _Multiplier_MultiplyFloat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiplier.proto",
}
